import React from 'react';
const Spinner = () => {
    return (React.createElement("svg", { xmlns: "http://www.w3.org/2000/svg", style: { margin: '0 auto', background: 'none', display: 'block' }, width: "200px", height: "200px", viewBox: "0 0 100 100", preserveAspectRatio: "xMidYMid" },
        React.createElement("g", { transform: "translate(80,50)" },
            React.createElement("g", { transform: "rotate(0)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "1" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.875s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.875s" })))),
        React.createElement("g", { transform: "translate(71.21320343559643,71.21320343559643)" },
            React.createElement("g", { transform: "rotate(45)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.875" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.75s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.75s" })))),
        React.createElement("g", { transform: "translate(50,80)" },
            React.createElement("g", { transform: "rotate(90)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.75" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.625s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.625s" })))),
        React.createElement("g", { transform: "translate(28.786796564403577,71.21320343559643)" },
            React.createElement("g", { transform: "rotate(135)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.625" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.5s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.5s" })))),
        React.createElement("g", { transform: "translate(20,50.00000000000001)" },
            React.createElement("g", { transform: "rotate(180)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.5" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.375s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.375s" })))),
        React.createElement("g", { transform: "translate(28.78679656440357,28.786796564403577)" },
            React.createElement("g", { transform: "rotate(225)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.375" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.25s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.25s" })))),
        React.createElement("g", { transform: "translate(49.99999999999999,20)" },
            React.createElement("g", { transform: "rotate(270)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.25" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "-0.125s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "-0.125s" })))),
        React.createElement("g", { transform: "translate(71.21320343559643,28.78679656440357)" },
            React.createElement("g", { transform: "rotate(315)" },
                React.createElement("circle", { cx: "0", cy: "0", r: "7", fill: "#1c4595", fillOpacity: "0.125" },
                    React.createElement("animateTransform", { attributeName: "transform", type: "scale", begin: "0s", values: "1.5 1.5;1 1", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite" }),
                    React.createElement("animate", { attributeName: "fillOpacity", keyTimes: "0;1", dur: "1s", repeatCount: "indefinite", values: "1;0", begin: "0s" }))))));
};
export default Spinner;
